sonar.projectKey=iagos-dc_iagos-python-libs
sonar.organization=iagos-dc
sonar.sources=packages/aeris-client/src
sonar.tests=packages/aeris-client/tests
sonar.python.version=3.10
sonar.sourceEncoding=UTF-8
